[project]
name = "multyscale"
description = "Composable multiscale spatial filtering models"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
keywords = [
    "visual perception",
    "spatial filtering",
    "multiscale",
    "computational modeling",
]

license = { file = "LICENSE" }
maintainers = [{ name = "Joris Vincent", email = "joris.vincent@tu-berlin.de" }]
version = "0.2.0"

requires-python = ">=3.8"
dependencies = ["numpy", "scipy", "matplotlib", "Pillow"]

[project.optional-dependencies]
dev = ["pytest", "black", "pyupgrade", "flake8"]
docs = [
    "jupyter-book",
    "jupytext>=1.13.3",
    "jupyterlab_myst",
    "myst_nb",
    "sphinx-hoverxref",
]

[project.urls]
repository = "https://github.com/computational-psychology/stimupy.git"

[build-system]
requires = ["setuptools >= 40.9.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."] # list of folders that contain the packages (["."] by default)
include = [
    "multyscale*",
] # package names should match these glob patterns (["*"] by default)
namespaces = false # to disable scanning PEP 420 namespaces (true by default)

[tool.semantic_release]
commit_message = "v{version}\n\nThis commit was automatically generated by python-semantic-release"
major_on_zero = false
tag_format = "v{version}"
version_variables = [ # version location(s)
    "multyscale/__init__.py:__version__", # in the init.py, so that multyscale.__version__ works
    "pyproject.toml:version",             # in this pyproject.toml
]
build_command = "pip3 install --upgrade build; python3 -m build"

[tool.semantic_release.branches.main]
match = "(main|master|build_.*)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.remote]
name = "tubgitlab"
type = "gitlab"

# [tool.semantic_release.publish]
# upload_to_vcs_release = true # upload sdist, wheel to release-tag


[tool.black]
line-length = 99
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 99

[tool.codespell]
skip = "./docs/_build/*,*.ipynb"
#exclude-file = ".codespell.ignore"
